kind: pipeline
type: kubernetes
name: default
steps:
  - name: build-image
    image: plugins/docker
    pull: if-not-exists
    settings:
      platform: linux/arm64
      repo: xbclub/drone-aliyun-esa-ssl-deploy
      environment:
        - DOCKER_BUILDKIT: 1
      tag:
        - latest-arm64
      username:
        from_secret: DOCKER_SELF_USERNAME
      password:
        from_secret: DOCKER_SELF_PASSWORD
      purge: false
  - name: build-image-amd64
    image: plugins/docker
    pull: if-not-exists
    settings:
      platform: linux/amd64
      repo: xbclub/drone-aliyun-esa-ssl-deploy
      tag:
        - latest-amd64
      username:
        from_secret: DOCKER_SELF_USERNAME
      password:
        from_secret: DOCKER_SELF_PASSWORD
      purge: false
    depends_on:
      - build-image
  - name: mergeimages
    image: plugins/manifest
    settings:
      username:
        from_secret: DOCKER_SELF_USERNAME
      password:
        from_secret: DOCKER_SELF_PASSWORD
      target: xbclub/drone-aliyun-esa-ssl-deploy:latest
      template: xbclub/drone-aliyun-esa-ssl-deploy:latest-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
        - latest
    depends_on:
      - build-image-amd64
      - build-image
trigger:
  branch:
    - main
  event:
    - tag
    - manual
node_selector:
  kubernetes.io/arch: "amd64"